"""baseline

Revision ID: 20260604_0001
Revises: 
Create Date: 2026-06-04 12:25:08.040196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260604_0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('criteria_type', sa.String(length=50), nullable=True),
    sa.Column('criteria_value', sa.Integer(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_badges_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_badges_slug'), ['slug'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('headline', sa.String(length=160), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('banner', sa.String(length=255), nullable=True),
    sa.Column('skills', sa.String(length=500), nullable=True),
    sa.Column('twitter', sa.String(length=255), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('github', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('featured_blog_id', sa.Integer(), nullable=True),
    sa.Column('featured_project_id', sa.Integer(), nullable=True),
    sa.Column('pending_email', sa.String(length=255), nullable=True),
    sa.Column('email_on_messages', sa.Boolean(), nullable=False),
    sa.Column('email_on_comments', sa.Boolean(), nullable=False),
    sa.Column('email_on_follows', sa.Boolean(), nullable=False),
    sa.Column('email_on_likes', sa.Boolean(), nullable=False),
    sa.Column('weekly_digest', sa.Boolean(), nullable=False),
    sa.Column('message_permission', sa.String(length=20), nullable=False),
    sa.Column('profile_views_count', sa.Integer(), nullable=False),
    sa.Column('xp_total', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('profile_xp_awarded_at', sa.DateTime(), nullable=True),
    sa.Column('reputation_points', sa.Integer(), nullable=False),
    sa.Column('trust_level', sa.Integer(), nullable=False),
    sa.Column('contributor_tier', sa.String(length=30), nullable=False),
    sa.Column('is_verified_creator', sa.Boolean(), nullable=False),
    sa.Column('open_to_work', sa.Boolean(), nullable=False),
    sa.Column('availability_status', sa.String(length=30), nullable=False),
    sa.Column('job_title', sa.String(length=160), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('preferred_work_type', sa.String(length=30), nullable=True),
    sa.Column('is_recruiter', sa.Boolean(), nullable=False),
    sa.Column('robotics_specialties', sa.Text(), nullable=True),
    sa.Column('portfolio_score', sa.Integer(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_featured_blog_id'), ['featured_blog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_featured_project_id'), ['featured_project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_reputation_points'), ['reputation_points'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_xp_total'), ['xp_total'], unique=False)

    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.String(length=500), nullable=True),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reading_time', sa.Integer(), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blogs_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blogs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blogs_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blogs_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_blogs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_blogs_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('demo_url', sa.String(length=500), nullable=True),
    sa.Column('stars_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_username', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_path', sa.String(length=255), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_username'), ['actor_username'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target_id'), ['target_id'], unique=False)

    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_block_pair')
    )
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocks_blocked_id'), ['blocked_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocks_blocker_id'), ['blocker_id'], unique=False)

    op.create_table('blog_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'blog_id', name='uq_blog_like')
    )
    with op.batch_alter_table('blog_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_likes_blog_id'), ['blog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_likes_user_id'), ['user_id'], unique=False)

    op.create_table('blog_tags',
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blog_id', 'tag_id')
    )
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'blog_id', name='uq_bookmark')
    )
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookmarks_blog_id'), ['blog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookmarks_user_id'), ['user_id'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_blog_id'), ['blog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_user_id'), ['user_id'], unique=False)

    op.create_table('community_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('post_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_posts_post_type'), ['post_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_posts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_posts_user_id'), ['user_id'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_slug'), ['slug'], unique=True)

    op.create_table('deleted_content_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_username', sa.String(length=50), nullable=True),
    sa.Column('content_data', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('recovered', sa.Boolean(), nullable=False),
    sa.Column('recovered_at', sa.DateTime(), nullable=True),
    sa.Column('recovered_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recovered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deleted_content_archive', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deleted_content_archive_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deleted_content_archive_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_deleted_content_archive_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deleted_content_archive_deleted_by_id'), ['deleted_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deleted_content_archive_expires_at'), ['expires_at'], unique=False)

    op.create_table('devlogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('milestone', sa.String(length=160), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('reposts_count', sa.Integer(), nullable=False),
    sa.Column('bookmarks_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devlogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devlogs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_devlogs_is_pinned'), ['is_pinned'], unique=False)
        batch_op.create_index(batch_op.f('ix_devlogs_progress'), ['progress'], unique=False)
        batch_op.create_index(batch_op.f('ix_devlogs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devlogs_visibility'), ['visibility'], unique=False)

    op.create_table('donation_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('upi_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donation_intents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donation_intents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_donation_intents_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_donation_intents_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_donation_intents_status'), ['status'], unique=False)
        batch_op.create_index('ix_donation_intents_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_donation_intents_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_donation_intents_user_id'), ['user_id'], unique=False)

    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followed_id', name='uq_follow_pair')
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follows_followed_id'), ['followed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follows_follower_id'), ['follower_id'], unique=False)

    op.create_table('leaderboard_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('period_key', sa.String(length=20), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period', 'period_key', name='uq_leaderboard_entry')
    )
    with op.batch_alter_table('leaderboard_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leaderboard_snapshots_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaderboard_snapshots_period_key'), ['period_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaderboard_snapshots_user_id'), ['user_id'], unique=False)

    op.create_table('login_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=160), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('fingerprint', sa.String(length=128), nullable=True),
    sa.Column('suspicious', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_events_email'), ['email'], unique=False)
        batch_op.create_index('ix_login_events_email_created', ['email', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_events_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_events_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_events_success'), ['success'], unique=False)
        batch_op.create_index('ix_login_events_success_created', ['success', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_events_suspicious'), ['suspicious'], unique=False)
        batch_op.create_index('ix_login_events_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_events_user_id'), ['user_id'], unique=False)

    op.create_table('login_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('device_label', sa.String(length=160), nullable=True),
    sa.Column('browser', sa.String(length=80), nullable=True),
    sa.Column('platform', sa.String(length=80), nullable=True),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_sessions_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_sessions_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_sessions_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_sessions_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_sessions_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_login_sessions_revoked_at'), ['revoked_at'], unique=False)
        batch_op.create_index('ix_login_sessions_user_fingerprint', ['user_id', 'fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_login_sessions_user_revoked_seen', ['user_id', 'revoked_at', 'last_seen_at'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachment_filename', sa.String(length=255), nullable=True),
    sa.Column('attachment_original_name', sa.String(length=255), nullable=True),
    sa.Column('attachment_mime', sa.String(length=120), nullable=True),
    sa.Column('attachment_size', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('email_status', sa.String(length=30), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_delivered_at'), ['delivered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_email_status'), ['email_status'], unique=False)
        batch_op.create_index('ix_notifications_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_from_user_id'), ['from_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_user_read_created', ['user_id', 'is_read', 'created_at'], unique=False)

    op.create_table('otp_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_tokens_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('portfolio_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('portfolio_strength', sa.Integer(), nullable=True),
    sa.Column('hiring_readiness', sa.Integer(), nullable=True),
    sa.Column('frontend_score', sa.Integer(), nullable=True),
    sa.Column('backend_score', sa.Integer(), nullable=True),
    sa.Column('project_depth', sa.Integer(), nullable=True),
    sa.Column('ai_ml_score', sa.Integer(), nullable=True),
    sa.Column('robotics_score', sa.Integer(), nullable=True),
    sa.Column('open_source_score', sa.Integer(), nullable=True),
    sa.Column('writing_quality', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_analyses_analyzed_at'), ['analyzed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_analyses_user_id'), ['user_id'], unique=False)

    op.create_table('project_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_images_project_id'), ['project_id'], unique=False)

    op.create_table('project_stars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_project_star')
    )
    with op.batch_alter_table('project_stars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_stars_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_stars_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_stars_user_id'), ['user_id'], unique=False)

    op.create_table('project_tags',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'tag_id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('reported_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('details', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_reported_user_id'), ['reported_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)

    op.create_table('robotics_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('project_type', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('demo_url', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('hardware_specs', sa.Text(), nullable=True),
    sa.Column('bom_data', sa.Text(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('stars_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('robotics_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_robotics_projects_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_robotics_projects_project_type'), ['project_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_robotics_projects_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_robotics_projects_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_robotics_projects_user_id'), ['user_id'], unique=False)

    op.create_table('streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current', sa.Integer(), nullable=False),
    sa.Column('longest', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('streaks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_streaks_user_id'), ['user_id'], unique=False)

    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=180), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('handled_by_id', sa.Integer(), nullable=True),
    sa.Column('admin_note', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['handled_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_tickets_category'), ['category'], unique=False)
        batch_op.create_index('ix_support_tickets_category_status', ['category', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_support_tickets_status'), ['status'], unique=False)
        batch_op.create_index('ix_support_tickets_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_user_id'), ['user_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_teams_visibility'), ['visibility'], unique=False)

    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='uq_user_badge')
    )
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_badges_badge_id'), ['badge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_badges_user_id'), ['user_id'], unique=False)

    op.create_table('xp_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(), nullable=False),
    sa.Column('bucket_key', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'action', 'bucket_key', name='uq_xp_bucket_once'),
    sa.UniqueConstraint('user_id', 'action', 'source_type', 'source_id', name='uq_xp_source_once')
    )
    with op.batch_alter_table('xp_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_xp_transactions_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_xp_transactions_awarded_at'), ['awarded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_xp_transactions_bucket_key'), ['bucket_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_xp_transactions_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_xp_transactions_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_xp_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('devlog_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('devlog_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['devlog_id'], ['devlogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'devlog_id', name='uq_devlog_bookmark')
    )
    with op.batch_alter_table('devlog_bookmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devlog_bookmarks_devlog_id'), ['devlog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devlog_bookmarks_user_id'), ['user_id'], unique=False)

    op.create_table('devlog_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('devlog_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['devlog_id'], ['devlogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devlog_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devlog_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_devlog_comments_devlog_id'), ['devlog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devlog_comments_user_id'), ['user_id'], unique=False)

    op.create_table('devlog_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('devlog_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['devlog_id'], ['devlogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'devlog_id', name='uq_devlog_like')
    )
    with op.batch_alter_table('devlog_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devlog_likes_devlog_id'), ['devlog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devlog_likes_user_id'), ['user_id'], unique=False)

    op.create_table('devlog_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('alt_text', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('devlog_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['devlog_id'], ['devlogs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devlog_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devlog_media_devlog_id'), ['devlog_id'], unique=False)

    op.create_table('devlog_reposts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('devlog_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['devlog_id'], ['devlogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'devlog_id', name='uq_devlog_repost')
    )
    with op.batch_alter_table('devlog_reposts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devlog_reposts_devlog_id'), ['devlog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devlog_reposts_user_id'), ['user_id'], unique=False)

    op.create_table('devlog_tags',
    sa.Column('devlog_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['devlog_id'], ['devlogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('devlog_id', 'tag_id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('job_type', sa.String(length=30), nullable=False),
    sa.Column('work_mode', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('experience_level', sa.String(length=30), nullable=True),
    sa.Column('skills_required', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applications_count', sa.Integer(), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('posted_by_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_jobs_company_status', ['company_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_posted_by_id'), ['posted_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_jobs_status_category_type_mode', ['status', 'category', 'job_type', 'work_mode'], unique=False)
        batch_op.create_index('ix_jobs_status_created', ['status', 'created_at'], unique=False)

    op.create_table('robotics_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['robotics_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('robotics_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_robotics_files_file_type'), ['file_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_robotics_files_project_id'), ['project_id'], unique=False)

    op.create_table('robotics_project_tags',
    sa.Column('robotics_project_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['robotics_project_id'], ['robotics_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('robotics_project_id', 'tag_id')
    )
    op.create_table('team_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=True),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'invitee_id', 'status', name='uq_team_invitation_status')
    )
    with op.batch_alter_table('team_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_invitations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invitations_invitee_id'), ['invitee_id'], unique=False)
        batch_op.create_index('ix_team_invitations_invitee_status', ['invitee_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invitations_inviter_id'), ['inviter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invitations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invitations_team_id'), ['team_id'], unique=False)

    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_member')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_team_members_user_role', ['user_id', 'role'], unique=False)

    op.create_table('activity_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_updates_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_updates_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_updates_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_activity_updates_job_created', ['job_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_updates_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_activity_updates_project_created', ['project_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_updates_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_activity_updates_team_created', ['team_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_updates_team_id'), ['team_id'], unique=False)

    op.create_table('collaboration_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('requested_role', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collaboration_requests', schema=None) as batch_op:
        batch_op.create_index('ix_collab_requests_recipient_status', ['recipient_id', 'status'], unique=False)
        batch_op.create_index('ix_collab_requests_requester_status', ['requester_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_requests_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_requests_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_requests_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_requests_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaboration_requests_team_id'), ['team_id'], unique=False)

    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cover_note', sa.Text(), nullable=True),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('recruiter_response', sa.String(length=1000), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'user_id', name='uq_job_application')
    )
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_applications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_applications_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_job_applications_job_status_created', ['job_id', 'status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_applications_reviewed_by_id'), ['reviewed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_applications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_applications_status_changed_at'), ['status_changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_applications_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_job_applications_user_status_created', ['user_id', 'status', 'created_at'], unique=False)

    op.create_table('job_saves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_job_save')
    )
    with op.batch_alter_table('job_saves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_saves_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_saves_user_id'), ['user_id'], unique=False)

    if op.get_bind().dialect.name == 'postgresql':
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
        op.execute(
            """
            CREATE INDEX ix_blogs_search_vector ON blogs USING GIN (
                (
                    setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
                    setweight(to_tsvector('english', coalesce(excerpt, '')), 'B') ||
                    setweight(to_tsvector('english', coalesce(content, '')), 'C')
                )
            )
            """
        )
        op.execute("CREATE INDEX ix_blogs_title_trgm ON blogs USING GIN (title gin_trgm_ops)")
        op.execute(
            """
            CREATE INDEX ix_projects_search_vector ON projects USING GIN (
                (
                    setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
                    setweight(to_tsvector('english', coalesce(description, '')), 'B')
                )
            )
            """
        )
        op.execute("CREATE INDEX ix_projects_title_trgm ON projects USING GIN (title gin_trgm_ops)")
        op.execute(
            """
            CREATE INDEX ix_jobs_search_vector ON jobs USING GIN (
                (
                    setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
                    setweight(to_tsvector('english', coalesce(description, '')), 'B') ||
                    setweight(to_tsvector('english', coalesce(skills_required, '')), 'A') ||
                    setweight(to_tsvector('english', coalesce(location, '')), 'C')
                )
            )
            """
        )
        op.execute("CREATE INDEX ix_jobs_title_trgm ON jobs USING GIN (title gin_trgm_ops)")
        op.execute("CREATE INDEX ix_users_username_trgm ON users USING GIN (username gin_trgm_ops)")
        op.execute("CREATE INDEX ix_users_skills_trgm ON users USING GIN (skills gin_trgm_ops)")
        op.execute("CREATE INDEX ix_tags_name_trgm ON tags USING GIN (name gin_trgm_ops)")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("DROP INDEX IF EXISTS ix_tags_name_trgm")
        op.execute("DROP INDEX IF EXISTS ix_users_skills_trgm")
        op.execute("DROP INDEX IF EXISTS ix_users_username_trgm")
        op.execute("DROP INDEX IF EXISTS ix_jobs_title_trgm")
        op.execute("DROP INDEX IF EXISTS ix_jobs_search_vector")
        op.execute("DROP INDEX IF EXISTS ix_projects_title_trgm")
        op.execute("DROP INDEX IF EXISTS ix_projects_search_vector")
        op.execute("DROP INDEX IF EXISTS ix_blogs_title_trgm")
        op.execute("DROP INDEX IF EXISTS ix_blogs_search_vector")
    with op.batch_alter_table('job_saves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_saves_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_saves_job_id'))

    op.drop_table('job_saves')
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_index('ix_job_applications_user_status_created')
        batch_op.drop_index(batch_op.f('ix_job_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_applications_status_changed_at'))
        batch_op.drop_index(batch_op.f('ix_job_applications_status'))
        batch_op.drop_index(batch_op.f('ix_job_applications_reviewed_by_id'))
        batch_op.drop_index('ix_job_applications_job_status_created')
        batch_op.drop_index(batch_op.f('ix_job_applications_job_id'))
        batch_op.drop_index(batch_op.f('ix_job_applications_created_at'))

    op.drop_table('job_applications')
    with op.batch_alter_table('collaboration_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collaboration_requests_team_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_requests_status'))
        batch_op.drop_index(batch_op.f('ix_collaboration_requests_requester_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_requests_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_requests_project_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_requests_job_id'))
        batch_op.drop_index(batch_op.f('ix_collaboration_requests_created_at'))
        batch_op.drop_index('ix_collab_requests_requester_status')
        batch_op.drop_index('ix_collab_requests_recipient_status')

    op.drop_table('collaboration_requests')
    with op.batch_alter_table('activity_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_updates_team_id'))
        batch_op.drop_index('ix_activity_updates_team_created')
        batch_op.drop_index(batch_op.f('ix_activity_updates_project_id'))
        batch_op.drop_index('ix_activity_updates_project_created')
        batch_op.drop_index(batch_op.f('ix_activity_updates_job_id'))
        batch_op.drop_index('ix_activity_updates_job_created')
        batch_op.drop_index(batch_op.f('ix_activity_updates_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_updates_actor_id'))
        batch_op.drop_index(batch_op.f('ix_activity_updates_action'))

    op.drop_table('activity_updates')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index('ix_team_members_user_role')
        batch_op.drop_index(batch_op.f('ix_team_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_role'))

    op.drop_table('team_members')
    with op.batch_alter_table('team_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_invitations_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_invitations_status'))
        batch_op.drop_index(batch_op.f('ix_team_invitations_inviter_id'))
        batch_op.drop_index('ix_team_invitations_invitee_status')
        batch_op.drop_index(batch_op.f('ix_team_invitations_invitee_id'))
        batch_op.drop_index(batch_op.f('ix_team_invitations_created_at'))

    op.drop_table('team_invitations')
    op.drop_table('robotics_project_tags')
    with op.batch_alter_table('robotics_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_robotics_files_project_id'))
        batch_op.drop_index(batch_op.f('ix_robotics_files_file_type'))

    op.drop_table('robotics_files')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status_created')
        batch_op.drop_index('ix_jobs_status_category_type_mode')
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_slug'))
        batch_op.drop_index(batch_op.f('ix_jobs_posted_by_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_jobs_created_at'))
        batch_op.drop_index('ix_jobs_company_status')
        batch_op.drop_index(batch_op.f('ix_jobs_company_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_category'))

    op.drop_table('jobs')
    op.drop_table('devlog_tags')
    with op.batch_alter_table('devlog_reposts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devlog_reposts_user_id'))
        batch_op.drop_index(batch_op.f('ix_devlog_reposts_devlog_id'))

    op.drop_table('devlog_reposts')
    with op.batch_alter_table('devlog_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devlog_media_devlog_id'))

    op.drop_table('devlog_media')
    with op.batch_alter_table('devlog_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devlog_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_devlog_likes_devlog_id'))

    op.drop_table('devlog_likes')
    with op.batch_alter_table('devlog_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devlog_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_devlog_comments_devlog_id'))
        batch_op.drop_index(batch_op.f('ix_devlog_comments_created_at'))

    op.drop_table('devlog_comments')
    with op.batch_alter_table('devlog_bookmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devlog_bookmarks_user_id'))
        batch_op.drop_index(batch_op.f('ix_devlog_bookmarks_devlog_id'))

    op.drop_table('devlog_bookmarks')
    with op.batch_alter_table('xp_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xp_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_xp_transactions_source_type'))
        batch_op.drop_index(batch_op.f('ix_xp_transactions_source_id'))
        batch_op.drop_index(batch_op.f('ix_xp_transactions_bucket_key'))
        batch_op.drop_index(batch_op.f('ix_xp_transactions_awarded_at'))
        batch_op.drop_index(batch_op.f('ix_xp_transactions_action'))

    op.drop_table('xp_transactions')
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_badges_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_badges_badge_id'))

    op.drop_table('user_badges')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_visibility'))
        batch_op.drop_index(batch_op.f('ix_teams_slug'))
        batch_op.drop_index(batch_op.f('ix_teams_owner_id'))
        batch_op.drop_index(batch_op.f('ix_teams_created_at'))

    op.drop_table('teams')
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_tickets_user_id'))
        batch_op.drop_index('ix_support_tickets_status_created')
        batch_op.drop_index(batch_op.f('ix_support_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_public_id'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_priority'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_email'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_created_at'))
        batch_op.drop_index('ix_support_tickets_category_status')
        batch_op.drop_index(batch_op.f('ix_support_tickets_category'))

    op.drop_table('support_tickets')
    with op.batch_alter_table('streaks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_streaks_user_id'))

    op.drop_table('streaks')
    with op.batch_alter_table('robotics_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_robotics_projects_user_id'))
        batch_op.drop_index(batch_op.f('ix_robotics_projects_status'))
        batch_op.drop_index(batch_op.f('ix_robotics_projects_slug'))
        batch_op.drop_index(batch_op.f('ix_robotics_projects_project_type'))
        batch_op.drop_index(batch_op.f('ix_robotics_projects_created_at'))

    op.drop_table('robotics_projects')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_reports_reported_user_id'))
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))

    op.drop_table('reports')
    op.drop_table('project_tags')
    with op.batch_alter_table('project_stars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_stars_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_stars_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_stars_created_at'))

    op.drop_table('project_stars')
    with op.batch_alter_table('project_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_images_project_id'))

    op.drop_table('project_images')
    with op.batch_alter_table('portfolio_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_analyses_analyzed_at'))

    op.drop_table('portfolio_analyses')
    with op.batch_alter_table('otp_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_otp_tokens_purpose'))
        batch_op.drop_index(batch_op.f('ix_otp_tokens_expires_at'))

    op.drop_table('otp_tokens')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read_created')
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_priority'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_from_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_entity_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_entity_id'))
        batch_op.drop_index('ix_notifications_entity')
        batch_op.drop_index(batch_op.f('ix_notifications_email_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_delivered_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_action'))

    op.drop_table('notifications')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_messages_is_read'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))

    op.drop_table('messages')
    with op.batch_alter_table('login_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_login_sessions_user_revoked_seen')
        batch_op.drop_index(batch_op.f('ix_login_sessions_user_id'))
        batch_op.drop_index('ix_login_sessions_user_fingerprint')
        batch_op.drop_index(batch_op.f('ix_login_sessions_revoked_at'))
        batch_op.drop_index(batch_op.f('ix_login_sessions_public_id'))
        batch_op.drop_index(batch_op.f('ix_login_sessions_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_login_sessions_is_current'))
        batch_op.drop_index(batch_op.f('ix_login_sessions_ip_address'))
        batch_op.drop_index(batch_op.f('ix_login_sessions_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_login_sessions_created_at'))

    op.drop_table('login_sessions')
    with op.batch_alter_table('login_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_events_user_id'))
        batch_op.drop_index('ix_login_events_user_created')
        batch_op.drop_index(batch_op.f('ix_login_events_suspicious'))
        batch_op.drop_index('ix_login_events_success_created')
        batch_op.drop_index(batch_op.f('ix_login_events_success'))
        batch_op.drop_index(batch_op.f('ix_login_events_ip_address'))
        batch_op.drop_index(batch_op.f('ix_login_events_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_login_events_event_type'))
        batch_op.drop_index('ix_login_events_email_created')
        batch_op.drop_index(batch_op.f('ix_login_events_email'))
        batch_op.drop_index(batch_op.f('ix_login_events_created_at'))

    op.drop_table('login_events')
    with op.batch_alter_table('leaderboard_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leaderboard_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_leaderboard_snapshots_period_key'))
        batch_op.drop_index(batch_op.f('ix_leaderboard_snapshots_period'))

    op.drop_table('leaderboard_snapshots')
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follows_follower_id'))
        batch_op.drop_index(batch_op.f('ix_follows_followed_id'))

    op.drop_table('follows')
    with op.batch_alter_table('donation_intents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donation_intents_user_id'))
        batch_op.drop_index('ix_donation_intents_user_created')
        batch_op.drop_index('ix_donation_intents_status_created')
        batch_op.drop_index(batch_op.f('ix_donation_intents_status'))
        batch_op.drop_index(batch_op.f('ix_donation_intents_public_id'))
        batch_op.drop_index(batch_op.f('ix_donation_intents_ip_address'))
        batch_op.drop_index(batch_op.f('ix_donation_intents_created_at'))

    op.drop_table('donation_intents')
    with op.batch_alter_table('devlogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devlogs_visibility'))
        batch_op.drop_index(batch_op.f('ix_devlogs_user_id'))
        batch_op.drop_index(batch_op.f('ix_devlogs_progress'))
        batch_op.drop_index(batch_op.f('ix_devlogs_is_pinned'))
        batch_op.drop_index(batch_op.f('ix_devlogs_created_at'))

    op.drop_table('devlogs')
    with op.batch_alter_table('deleted_content_archive', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deleted_content_archive_expires_at'))
        batch_op.drop_index(batch_op.f('ix_deleted_content_archive_deleted_by_id'))
        batch_op.drop_index(batch_op.f('ix_deleted_content_archive_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_deleted_content_archive_content_type'))
        batch_op.drop_index(batch_op.f('ix_deleted_content_archive_content_id'))

    op.drop_table('deleted_content_archive')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_slug'))
        batch_op.drop_index(batch_op.f('ix_companies_created_by_id'))

    op.drop_table('companies')
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_posts_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_posts_status'))
        batch_op.drop_index(batch_op.f('ix_community_posts_post_type'))
        batch_op.drop_index(batch_op.f('ix_community_posts_created_at'))

    op.drop_table('community_posts')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_comments_parent_id'))
        batch_op.drop_index(batch_op.f('ix_comments_created_at'))
        batch_op.drop_index(batch_op.f('ix_comments_blog_id'))

    op.drop_table('comments')
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmarks_user_id'))
        batch_op.drop_index(batch_op.f('ix_bookmarks_blog_id'))

    op.drop_table('bookmarks')
    op.drop_table('blog_tags')
    with op.batch_alter_table('blog_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_blog_likes_blog_id'))

    op.drop_table('blog_likes')
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocks_blocker_id'))
        batch_op.drop_index(batch_op.f('ix_blocks_blocked_id'))

    op.drop_table('blocks')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_ip_address'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_username'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_slug'))
        batch_op.drop_index(batch_op.f('ix_projects_created_at'))
        batch_op.drop_index(batch_op.f('ix_projects_category_id'))

    op.drop_table('projects')
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blogs_user_id'))
        batch_op.drop_index(batch_op.f('ix_blogs_status'))
        batch_op.drop_index(batch_op.f('ix_blogs_slug'))
        batch_op.drop_index(batch_op.f('ix_blogs_published_at'))
        batch_op.drop_index(batch_op.f('ix_blogs_created_at'))
        batch_op.drop_index(batch_op.f('ix_blogs_category_id'))

    op.drop_table('blogs')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_slug'))

    op.drop_table('categories')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_xp_total'))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_reputation_points'))
        batch_op.drop_index(batch_op.f('ix_users_level'))
        batch_op.drop_index(batch_op.f('ix_users_featured_project_id'))
        batch_op.drop_index(batch_op.f('ix_users_featured_blog_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_slug'))

    op.drop_table('tags')
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_badges_slug'))
        batch_op.drop_index(batch_op.f('ix_badges_category'))

    op.drop_table('badges')
    # ### end Alembic commands ###
